######################################################################
# Automatically generated by qmake (3.1) Tue Jul 25 08:58:25 2017
######################################################################
# Note:
#  In case of library conflict, remove DYLD_LIBRARY_PATH to /Library/Frameworks/SentechSDK.framework/* from run environment of Qt Creator.

QT += core gui widgets
CONFIG += c++11
TEMPLATE = app
TARGET = Overlay
unix:macx:{
FRAMEWORKPATH = /Library/Frameworks/SentechSDK.framework

INCLUDEPATH += $${FRAMEWORKPATH}/Headers \
    $${FRAMEWORKPATH}/Headers/GenICam \
    $${FRAMEWORKPATH}/Headers/StApi 

LIBS += -L$${FRAMEWORKPATH}/Libraries/GenICam -lGCBase -lGenApi \
     -L$${FRAMEWORKPATH}/Libraries -lStApi_TL -lStApi_GUI_qt
}

unix:!macx:{
INCLUDEPATH += $(STAPI_ROOT_PATH)/include/GenICam \
    $(STAPI_ROOT_PATH)/include/StApi 
LIBS += -L$(STAPI_ROOT_PATH)/lib/GenICam \
    -lGCBase \
    -lGenApi \
    -L$(STAPI_ROOT_PATH)/lib \
    -lStApi_TL -lStApi_GUI_qt
}

# Input
SOURCES += Overlay.cpp
